import { Routes } from '@angular/router';
import { LandingPageComponent } from './components/landing-page/landing-page.component';
import { ContactMeComponent } from './components/contact-me/contact-me.component';
import { PrivacyComponent } from './components/privacy/privacy.component';
import { AboutComponent } from './components/about/about.component';
import { NotFoundComponent } from './components/not-found/not-found.component';
import { ExerciseListComponent } from './components/body-components/exercise-list/exercise-list.component';
import { BlogListComponent } from './components/body-components/blog-list/blog-list.component';
import { BlogItemComponent } from './components/body-components/blog-item/blog-item.component';
import { ExerciseItemComponent } from './components/body-components/exercise-item/exercise-item.component';
import { ExerciseEditComponent } from './components/body-components/exercise-edit/exercise-edit.component';
import { BlogEditComponent } from './components/body-components/blog-edit/blog-edit.component';
import { DownloadPageComponent } from './components/download-page/download-page.component';
import { LoginComponent } from './components/auth/login/login.component';
import { RegisterComponent } from './components/auth/register/register.component';
import { ForgotPasswordComponent } from './components/auth/forgot-password/forgot-password.component';
import { UserProfileComponent } from './components/auth/user-profile/user-profile.component';
import { ConfirmEmailComponent } from './components/auth/confirm-email/confirm-email.component';
import { authGuard } from './guards/auth.guard';

export const routes: Routes = [
  { path: '', component: LandingPageComponent },
  { path: 'login', component: LoginComponent },
  { path: 'register', component: RegisterComponent },
  { path: 'forgot-password', component: ForgotPasswordComponent },
  { path: 'confirm-email', component: ConfirmEmailComponent },
  { path: 'profile', component: UserProfileComponent, canActivate: [authGuard] },
  { path: 'blogs', component: BlogListComponent },
  { path: 'blogs/new', component: BlogEditComponent },
  { path: 'blogs/edit/:id', component: BlogEditComponent },
  { path: 'blogs/:id', component: BlogItemComponent },
  { path: 'exercises', component: ExerciseListComponent },
  { path: 'exercise/details/:id', component: ExerciseItemComponent },
  { path: 'exercise/edit/:id', component: ExerciseEditComponent },
  { path: 'exercise/new', component: ExerciseEditComponent },
  { path: 'contact', component: ContactMeComponent },
  { path: 'privacy', component: PrivacyComponent },
  { path: 'about', component: AboutComponent },
  { path: 'download', component: DownloadPageComponent },
  { path: '**', component: NotFoundComponent }
];
